name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: sudo ./.github/scripts/setup-linux.sh
    - name: Build
      run: make
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tronbyt
        path: |
          tronbyt
